// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfBtCSXAuzwBbM-HWy-oD3Ux3527j8gs',
    appId: '1:83824022955:android:0bdf3c2d9cb5094c5b2eee',
    messagingSenderId: '83824022955',
    projectId: 'favorite-place-8066c',
    databaseURL: 'https://favorite-place-8066c-default-rtdb.firebaseio.com',
    storageBucket: 'favorite-place-8066c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYfJSjDVUJ0jFC4-1Imb94OnUaoCBcqg',
    appId: '1:83824022955:ios:1c07701ab5c8877a5b2eee',
    messagingSenderId: '83824022955',
    projectId: 'favorite-place-8066c',
    databaseURL: 'https://favorite-place-8066c-default-rtdb.firebaseio.com',
    storageBucket: 'favorite-place-8066c.appspot.com',
    iosClientId: '83824022955-irv3f59gb18qbej59q07tqd6t47sndnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
